DROP TABLE visitation_log CASCADE CONSTRAINTS;
DROP TABLE medical_session CASCADE CONSTRAINTS;
DROP TABLE incident_report CASCADE CONSTRAINTS;
DROP TABLE guard CASCADE CONSTRAINTS;
DROP TABLE professional CASCADE CONSTRAINTS;
DROP TABLE inmate CASCADE CONSTRAINTS;
DROP TABLE visitor CASCADE CONSTRAINTS;
DROP TABLE cell CASCADE CONSTRAINTS;
DROP TABLE wing CASCADE CONSTRAINTS;
DROP TABLE staff CASCADE CONSTRAINTS;

DROP SEQUENCE inmate_seq;
DROP SEQUENCE staff_seq;
DROP SEQUENCE incident_seq;

COMMIT;